Query ergonomics
zio/zio-http pull request #1080
Opened 2022-02-21 14:26 UTC by gciuloaica

Implementation that supports:
- up to 22 parameters in Case Class
- unlimited cases in a sum type - but provides support only for `case object`
- primitives could be wrapped in `Option` or `List`

2022-02-24 09:23 UTC, smehta91 requested changes
We can build `DynamicValue` using QueryParameter domain and while decoding we can decode typed value if we have schema for the type

2022-02-24 09:23 UTC, smehta91 commented on zio-http/src/main/scala/zhttp/http/QueryParameters.scala
> +final case class QueryParameters(raw: Map[String, List[String]]) { self =>
This should use `DynamicValue` of ZSchema

2022-02-24 09:23 UTC, smehta91 commented on zio-http/src/main/scala/zhttp/http/QueryParameters.scala
> +}
```suggestion
final case class QueryParameters(raw: ListMap[String, DynamicValue]) { self =>
  def ++(other: QueryParameters): QueryParameters = self.combine(other)

  def combine(other: QueryParameters): QueryParameters = QueryParameters(self.raw ++ other.raw)

  def queryParams: QueryParameters = self
}

object QueryParameters {

  val empty: QueryParameters = QueryParameters(ListMap.empty[String, DynamicValue])

}
```

2022-02-24 09:23 UTC, smehta91 commented on zio-http-query-params/src/main/scala/zhttp/http/query/QueryParams.scala
> +      CaseClassDecoder.decode(schema, queryParams.raw)
`schema.fromDynamic(DynamicValue.Record(queryParams.raw))`

2022-04-19 08:19 UTC, gciuloaica commented
new API in progress https://github.com/dream11/zio-http/pull/1209

2022-04-19 08:19 UTC, closed without merging