Merge client and server request
zio/zio-http pull request #1125
Opened 2022-03-08 05:07 UTC by amitksingh1490

2022-03-08 10:33 UTC, gciuloaica approved these changes
looks good to me

2022-03-09 07:38 UTC, kaushik143 requested changes

2022-03-09 07:38 UTC, kaushik143 commented on zio-http/src/test/scala/zhttp/internal/HttpGen.scala
> +  def RequestGen[R](
Rename to `requestGen`

2022-03-09 07:38 UTC, kaushik143 commented on zio-http/src/test/scala/zhttp/internal/HttpGen.scala
> +      version <- Gen.fromIterable(List(Version.Http_1_0, Version.Http_1_1))
Can we create Gen for the version too? It has been used at couple of places

2022-03-09 07:38 UTC, kaushik143 commented on zio-http/src/test/scala/zhttp/http/EncodeClientRequestSpec.scala
> +  val anyClientParam: Gen[Random with Sized, Request] = HttpGen.RequestGen(
requestGen should be used as `HttpGen.requestGen`

2022-03-09 09:43 UTC, tusharmath commented on zio-http/src/main/scala/zhttp/service/Client.scala
>    def request(
```suggestion
  private [zhttp] def request(
```

2022-03-09 09:44 UTC, tusharmath commented on zio-http/src/test/scala/zhttp/http/EncodeClientRequestSpec.scala
>  object EncodeClientRequestSpec extends DefaultRunnableSpec with EncodeClientRequest {
```suggestion
object EncodeRequestSpec extends DefaultRunnableSpec with EncodeClientRequest {
```

2022-03-09 09:46 UTC, tusharmath commented on zio-http/src/main/scala/zhttp/service/Client.scala
> +  def request(request: Request, attribute: Attribute): Task[Response] =
```suggestion
  private [zhttp] def request(request: Request, attribute: Attribute): Task[Response] =
```

2022-03-09 09:54 UTC, amitksingh1490 commented on zio-http/src/main/scala/zhttp/service/Client.scala
> +  def request(request: Request, attribute: Attribute): Task[Response] =
Will Add a separate Ticket for this

2022-03-09 09:59 UTC, amitksingh1490 commented on zio-http/src/main/scala/zhttp/service/Client.scala
>    def request(
Will add a separate issue for this

2022-03-09 10:21 UTC, kaushik143 approved these changes

2022-03-09 10:21 UTC, merged