issue_685 Client default User Agent request header
zio/zio-http pull request #1181
Opened 2022-04-02 21:23 UTC by rajcspsg

this closes the issue https://github.com/dream11/zio-http/issues/685

2022-04-15 07:01 UTC, tusharmath commented
This looks good @rajcspsg !

Could you please add some unit tests also for this.

2022-04-15 07:35 UTC, rajcspsg commented
> This looks good @rajcspsg !
> 
> Could you please add some unit tests also for this.

@tusharmath could you please provide the link for existing test cases for http client. I tried to find but couldn't

2022-04-15 07:53 UTC, amitksingh1490 commented
> > This looks good @rajcspsg !
> > Could you please add some unit tests also for this.
> 
> @tusharmath could you please provide the link for existing test cases for http client. I tried to find but couldn't
Please check this
https://github.com/dream11/zio-http/blob/main/zio-http/src/test/scala/zhttp/service/ClientSpec.scala

2022-04-16 03:42 UTC, rajcspsg commented
@amitksingh1490 @tusharmath I've added unit test. could you please check again.

2022-04-18 06:53 UTC, tusharmath requested changes

2022-04-18 06:53 UTC, tusharmath commented on zio-http/src/main/scala/zhttp/service/Client.scala
> +  def createRequest(
I don't think we need this method.

2022-04-18 06:53 UTC, tusharmath commented on zio-http/src/main/scala/zhttp/service/Client.scala
> +  val zioHttpVersion: String           = Client.getClass().getPackage().getImplementationVersion()
- Use `CharSequence` instead of string
- Use `AsciiString.cached` to generate the char seqeuence.

2022-04-18 06:53 UTC, tusharmath commented on zio-http/src/test/scala/zhttp/service/ClientSpec.scala
> +        val request = Client.createRequest(url, headers = Headers.empty, addZioUserAgentHeader = true)
Unit test should work with `Client.request` we don't need to create a new method for this.

2022-06-28 14:33 UTC, rajcspsg commented
@tusharmath @amitksingh1490 could you please take a look at the PR and let me know in case if any update needed.

2022-07-06 03:15 UTC, rajcspsg commented
> @tusharmath @amitksingh1490 could you please take a look at the PR and let me know in case if any update needed.

@tusharmath @amitksingh1490 could you please take a look at this PR when you get chance.

2022-07-21 04:45 UTC, rajcspsg commented
@tusharmath @amitksingh1490 I've fixed the merge conflicts. Could you please check the PR once again

2022-07-25 20:16 UTC, rajcspsg commented
@tusharmath  @amitksingh1490  I've fixed the merge conflicts. Could you please check the PR once again

2022-07-25 20:19 UTC, rajcspsg commented on zio-http/src/main/scala/zhttp/service/Client.scala
> +  def createRequest(
I removed this method

2022-09-15 12:04 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/zio/zio-http?pullRequest=1181) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you all sign our [Contributor License Agreement](https://cla-assistant.io/zio/zio-http?pullRequest=1181) before we can accept your contribution.<br/>**1** out of **2** committers have signed the CLA.<br/><br/>:white_check_mark: vigoo<br/>:x: rajcspsg<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/zio/zio-http?pullRequest=1181) it.</sub>

2022-09-15 12:24 UTC, vigoo commented
@rajcspsg could you sign the Contributor License Agreement?

2022-09-15 13:20 UTC, rajcspsg commented
@vigoo Thanks I've signed the contributor agreement

2022-09-15 13:39 UTC, vigoo commented
thanks!

2022-09-15 13:39 UTC, vigoo approved these changes

2022-09-15 13:41 UTC, vigoo commented
Merging this because the concerns seems to be solved and the client interface is being redesigned in another PR anyway.

2022-09-15 13:42 UTC, merged