added implementation to prettify error message as middleware
zio/zio-http pull request #1334
Opened 2022-07-06 06:52 UTC by gciuloaica

2022-07-12 09:47 UTC, tusharmath commented
There are some places in the `Handler` also where we catch exceptions and create a 500 exception. Ideally, those too should handled by this middleware, otherwise we will have a bit of inconsistent way to display error messages.

2022-07-13 06:18 UTC, gciuloaica commented
> There are some places in the `Handler` also where we catch exceptions and create a 500 exception. Ideally, those too should handled by this middleware, otherwise we will have a bit of inconsistent way to display error messages.

@tusharmath the error handling in `Handler` are happening after the `HttpApp` has been evaluated, so the middleware execution has been completed (unsafeRun completed). One way to unify both parts will be to migrate the formatting code to a different place (outside middleware implementation) and re-use it in Handler. To implement this it will require to know in the Handler if the middleware is in the pipeline or not.

2022-09-15 15:23 UTC, jdegoes commented on zio-http/src/main/scala/zhttp/http/middleware/WebWithError.scala
> +class WebWithError {}
Dead code, let's delete

2022-09-15 15:24 UTC, jdegoes commented on zio-http/src/main/scala/zhttp/http/middleware/package.scala
> +  type HttpMiddlewareWithError[-R, +E] = MonoMiddleware[R, E, Option[Request], Option[Response]]
Dead alias, let's delete

2022-09-15 15:24 UTC, jdegoes commented on zio-http/src/main/scala/zhttp/service/Handler.scala
> +        unsafeRun(
These changes seem unnecessary for the scope of this PR. We should aim to do this as a "pure middleware" that does not touch anything else in the library.

2022-09-15 15:25 UTC, jdegoes requested changes
Would love to get this in!

Please address comments, fix conflicts, and rebase. Thank you!

2022-09-16 12:38 UTC, devsprint commented
Closing this in favor of #1492

2022-09-16 12:38 UTC, closed without merging