Simpler port
zio/zio-http pull request #1993
Opened 2023-02-12 22:26 UTC by Wosin

An idea to modify the current Config and Server layers to make it easier to start server on custom port.

2023-02-12 23:51 UTC, adamgfraser requested changes
The `()` after every usage of `Server.default` is very unidiomatic since this would normally indicate that this is a side effecting method. It also means that the `default` server is not a value that will automatically be memoized and shared during layer construction.

This can already be done as:

```scala
ServerConfig.live(ServerConfig.default.port(???)) >>> Server.live
```

This can potentially be shortened by introducing an overloaded `live` constructor on `Server` that takes a `ServerConfig` so the user does not need to manually compose the layers:

```scala
def live(serverConfig: ServerConfig): ZLayer[Any, Throwable, Server] =
  ServerConfig.live(serverConfig) >>> Server.live

Server.live(ServerConfig.default.port(???))
```

Or going a step further:

```scala
def defaultWith(f: ServerConfig => ServerConfig): ZLayer[Any, Throwable, Server] =
  live(f(ServerConfig.default))

Server.defaultWith(_.port(???))
```

Or even:

```scala
def defautlWithPort(port: Int): ZLayer[Any, Throwable, Server] =
  defaultWith(_.port(port))

Server.defaultWithPort(???)
```

These would not impact the ergonomics of the existing usage of the server and would support other modifications to the server configuration in a compositional way in addition to just the port.

2023-02-13 13:37 UTC, Wosin commented
Okay, that definitely looks better. Let me fix that.

2023-02-13 19:32 UTC, adamgfraser commented on zio-http/src/main/scala/zio/http/Server.scala
> +  def   install[R](httpApp: App[R], errorCallback: Option[ErrorCallback] = None)(implicit
Stray formatting change?

2023-02-13 19:33 UTC, adamgfraser commented on zio-http/src/main/scala/zio/http/Server.scala
> +  def live(conf: ServerConfig) = {
Very minor but no need for curly braces here.

2023-02-13 19:33 UTC, adamgfraser commented on zio-http/src/test/scala/zio/http/api/ServerClientIntegrationSpec.scala
> +      ServerConfig.live(),
Don't think this change should be necessary.

2023-02-13 19:34 UTC, adamgfraser commented on zio-http/src/main/scala/zio/http/ServerConfig.scala
> +  def default: ServerConfig = ServerConfig()
Don't think these changes should be necessary.

2023-02-15 06:08 UTC, adamgfraser commented on zio-http/src/main/scala/zio/http/Server.scala
> +  def live(conf: ServerConfig): ZLayer[Any, Throwable, Server] = {
If this is already going to be a `def` we can just accept a `Trace` as a parameter.

2023-02-15 22:26 UTC, adamgfraser approved these changes
Looks good!

2023-02-16 00:06 UTC, adamgfraser commented on zio-http/src/main/scala/zio/http/Server.scala
> +  def live(conf: ServerConfig)(implicit trace: Trace): ZLayer[Any, Throwable, Server] = {
Don't need the curly braces here.

2023-02-16 09:28 UTC, jdegoes approved these changes

2023-02-16 09:28 UTC, merged