add cookie helper
zio/zio-http pull request #2439
Opened 2023-09-08 19:59 UTC by TomTriple

2023-09-09 08:00 UTC, TomTriple commented
`zio.http.ClientHttpsSpec` seems flaky - running it locally works

2023-09-24 21:11 UTC, jdegoes commented on zio-http/src/main/scala/zio/http/Request.scala
> +  def cookieWith[R, A](name: String)(f: Cookie => ZIO[R, Throwable, A])(implicit trace: Trace): ZIO[R, Throwable, A] =
`cookieWithZIO`

2023-09-24 21:12 UTC, jdegoes commented on zio-http/src/main/scala/zio/http/Request.scala
> +  def cookies: Option[NonEmptyChunk[Cookie]] =
```suggestion
  def cookies: Chunk[Cookie] =
```

2023-09-24 21:14 UTC, jdegoes commented on zio-http/src/main/scala/zio/http/Request.scala
> +  def cookieWithOrFail[R, E, A](name: String)(e: E)(f: Cookie => ZIO[R, E, A])(implicit trace: Trace): ZIO[R, E, A] =
```suggestion
  def cookieWithOrFail[R, E, A](name: String)(missingCookieError: E)(f: Cookie => ZIO[R, E, A])(implicit trace: Trace): ZIO[R, E, A] =
```

2023-09-25 11:33 UTC, TomTriple commented
I added all your suggestions!

2023-09-25 15:04 UTC, TomTriple commented on zio-http/src/main/scala/zio/http/Request.scala
> +  def cookieWith[R, A](name: String)(f: Cookie => ZIO[R, Throwable, A])(implicit trace: Trace): ZIO[R, Throwable, A] =
done

2023-09-25 15:04 UTC, TomTriple commented on zio-http/src/main/scala/zio/http/Request.scala
> +  def cookies: Option[NonEmptyChunk[Cookie]] =
done

2023-09-25 15:04 UTC, TomTriple commented on zio-http/src/main/scala/zio/http/Request.scala
> +  def cookieWithOrFail[R, E, A](name: String)(e: E)(f: Cookie => ZIO[R, E, A])(implicit trace: Trace): ZIO[R, E, A] =
done

2023-09-25 20:08 UTC, 987Nabil requested changes

2023-09-25 20:08 UTC, 987Nabil commented on zio-http/src/main/scala/zio/http/Request.scala
> +    ZIO.getOrFailWith(e(new java.util.NoSuchElementException(s"cookie doesn't exist: $name")))(cookie(name)).flatMap(f)
This will create an exception with stacktrace just to be thrown away immediately. This does not seem to be efficient.
I'd change it just simply to 
```suggestion
    cookie(name) match {
      case Some(cookie) => f(e)
      case None => ZIO.fail(e)
    }
```
where e is not a function

2023-09-26 14:08 UTC, TomTriple commented on zio-http/src/main/scala/zio/http/Request.scala
> +    ZIO.getOrFailWith(e(new java.util.NoSuchElementException(s"cookie doesn't exist: $name")))(cookie(name)).flatMap(f)
Added your suggestions, thank you!

2023-09-27 08:51 UTC, jdegoes approved these changes

2023-09-27 08:51 UTC, merged