Schema based query codecs including validation (#2937)
zio/zio-http pull request #2999
Opened 2024-08-02 14:25 UTC by 987Nabil

This PR is based on the changes in #2991.
It encodes the optionality of the query params by adjusting the type hint and the binary codec.
This has multiple benefits.
1. the codecs are not blowing up the http codec alternatives when calculated
2. the more accurate modeling of the types for the query codec (Unit vs single value vs chunk) safes unnecessary chunk allocation when en/decoding
3. the change to BinaryCodecWithSchema allows us, to offer an API that manipulates the schema and generating a new codec from the changes schema. We could use this to add option or validation calls to the codec, instead of forcing the user to use zio-schema annotations on the data type. This would also work with primitive types. There would be no need to wrap them in a case class to annotate the field with validations.

fixes #2937
/claim #2937

2024-08-02 14:27 UTC, 987Nabil commented
This needs some migration with changes from other PRs

2024-08-03 08:54 UTC, jdegoes commented on zio-http/shared/src/main/scala/zio/http/codec/BinaryCodecWithSchema.scala
> +final case class BinaryCodecWithSchema[A](codecBuilder: CodecBuilder, schema: Schema[A]) {
I don't like the structure of this:

1. `CodecBuilder` says, "I can give you a binary codec for any schema"
2. `BinaryCodecWithSchema` says "Here is a schema and a way to get a binary codec for ANY schema"

Why was this change necessary?

2024-08-03 10:05 UTC, jdegoes commented on zio-http/shared/src/main/scala/zio/http/codec/QueryCodecs.scala
> +  def queryTo[A](name: String)(implicit codec: Schema[A]): QueryCodec[A] = singleValueCodec(name, codec)
Thinking about this more, I believe that if we have a schema, we should get the name from the field(s) inside the Schema. Rather than accepting it explicitly. So no `query*` method that takes a `Schema[A]` should also take a `String` name. We can get the arity from the schema too (if it's a sequence rather than a single one; NonEmptyChunk can take care of non-empty sequences). This also provides a path to deserializing multiple fields at once, which will solve the stack overflow problems.

2024-08-03 10:06 UTC, jdegoes requested changes
Definitely the right direction, but a few enhancements and modifications will help push this over the finish line.

2024-08-03 23:33 UTC, 987Nabil commented
closing in favor of #3000

2024-08-03 23:33 UTC, closed without merging