Fix OpenApi gen components from case class with arity > 22
zio/zio-http pull request #3065
Opened 2024-08-29 22:23 UTC by narma

Resolves #3064 
/claim  #3064 

Currently zio-schema derives schema for case classes with arity > 22 fields via Transform from/to map. Both For [scala 2](https://github.com/zio/zio-schema/blob/v1.4.0/zio-schema-derivation/shared/src/main/scala-2/zio/schema/DeriveSchema.scala#L380) and [scala 3](https://github.com/zio/zio-schema/blob/v1.4.0/zio-schema-derivation/shared/src/main/scala-3/zio/schema/DeriveSchema.scala#L305).

Current PR add support for this case as it done in other places, for example:
https://github.com/zio/zio-http/blob/b4dde6afae757d136885e08a263475c9abae329d/zio-http/shared/src/main/scala/zio/http/endpoint/openapi/JsonSchema.scala#L442
https://github.com/zio/zio-http/blob/b4dde6afae757d136885e08a263475c9abae329d/zio-http-cli/src/main/scala/zio/http/endpoint/cli/HttpOptions.scala#L142

2024-08-29 22:25 UTC, narma commented
Looks like current failure in test not related to this PR. Probably it because of https://github.com/zio/zio/issues/9152

2024-08-31 17:05 UTC, 987Nabil requested changes

2024-08-31 17:05 UTC, 987Nabil commented on zio-http-gen/src/test/scala/zio/http/gen/openapi/EndpointGenSpec.scala
> +        test("response are case class with 22+ fields") {
You need to add a test to the OpenAPIGenSepc. You can keep this spec, but please let it look like the other specs

2024-09-05 05:25 UTC, 987Nabil approved these changes

2024-09-05 05:25 UTC, merged