refactor: removed AliasModule
zio/zio-http pull request #316
Opened 2021-07-29 08:17 UTC by dinojohn

fixes #310

2021-07-29 08:26 UTC, amitksingh1490 requested changes

2021-07-29 08:26 UTC, amitksingh1490 commented on zio-http/src/main/scala/zhttp/http/Header.scala
> +  HttpHeaderNames => JHttpHeaderNames,
missed this

2021-07-29 08:26 UTC, amitksingh1490 commented on zio-http/src/main/scala/zhttp/service/ChannelFactory.scala
> +import io.netty.channel.epoll.{Epoll => JEpoll, EpollSocketChannel}
missed this

2021-07-29 17:56 UTC, tusharmath commented
Search for the following two reg-ex

```regex
import.*\{.*\n.*=>
```

```regex
import.*\{.*.*=>
```

2021-08-01 10:50 UTC, tusharmath commented on example/src/main/scala/HttpsClient.scala
> +  val env     = HChannelFactory.auto ++ HEventLoopGroup.auto()
Public API should not have `H` prefix.

2021-08-01 10:51 UTC, tusharmath commented on zio-http/src/main/scala/zhttp/service/ChannelFactory.scala
> +object HChannelFactory {
Public API should not have `H` prefix.

2021-08-02 09:55 UTC, tusharmath commented on zio-http/src/main/scala/zhttp/service/ChannelFactory.scala
> +import io.netty.channel.{Channel, ChannelFactory => HChannelFactory}
```suggestion
import io.netty.channel.{Channel, ChannelFactory => JChannelFactory}
```

2021-08-02 11:20 UTC, tusharmath commented on zio-http/src/main/scala/zhttp/socket/WebSocketFrame.scala
> +import io.netty.handler.codec.http.websocketx.{WebSocketFrame => HWebSocketFrame, _}
```suggestion
import io.netty.handler.codec.http.websocketx.{WebSocketFrame => JWebSocketFrame, _}
```

2021-08-02 11:22 UTC, tusharmath commented on zio-http/src/main/scala/zhttp/service/server/ServerChannelFactory.scala
> +import io.netty.channel.{ChannelFactory => HChannelFactory, ServerChannel}
```suggestion
import io.netty.channel.{ChannelFactory => JChannelFactory, ServerChannel}
```

2021-08-02 11:22 UTC, tusharmath commented on zio-http/src/main/scala/zhttp/service/package.scala
> +import io.netty.channel.{Channel, ChannelFactory => HChannelFactory, EventLoopGroup => HEventLoopGroup, ServerChannel}
```suggestion
import io.netty.channel.{Channel, ChannelFactory => JChannelFactory, EventLoopGroup => HEventLoopGroup, ServerChannel}
```

2021-08-02 11:25 UTC, tusharmath commented on zio-http/src/main/scala/zhttp/service/Client.scala
> +import io.netty.channel.{Channel, ChannelFactory => HChannelFactory, EventLoopGroup => HEventLoopGroup}
```suggestion
import io.netty.channel.{Channel, ChannelFactory => JChannelFactory, EventLoopGroup => HEventLoopGroup}
```

2021-08-02 11:25 UTC, tusharmath commented on zio-http/src/main/scala/zhttp/service/ChannelFactory.scala
> +import io.netty.channel.{Channel, ChannelFactory => HChannelFactory}
```suggestion
import io.netty.channel.{Channel, ChannelFactory => JChannelFactory}
```

2021-08-02 11:26 UTC, tusharmath commented on zio-http/src/main/scala/zhttp/http/Scheme.scala
> +import io.netty.handler.codec.http
```suggestion
import io.netty.handler.codec.http.{HttpScheme}
```

2021-08-03 09:00 UTC, tusharmath approved these changes

2021-08-03 09:18 UTC, merged