HTTP spec conformance during CI
zio/zio-http pull request #3169
Opened 2024-09-26 07:11 UTC by Saturn225

/claim #3083

2024-09-26 07:11 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/zio/zio-http?pullRequest=3169) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/zio/zio-http?pullRequest=3169) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/zio/zio-http?pullRequest=3169) it.</sub>

2024-09-26 21:25 UTC, 987Nabil commented
@Saturn225 HTTP/2 is out of scope. The failing test should be fixed first. I set this PR to draft for now. Once you fixed the issues open again. If you are stuck, you can contact me on discord

2024-10-01 18:07 UTC, 987Nabil commented on zio-http/jvm/src/main/scala/zio/http/netty/server/ServerInboundHandler.scala
> +    req.headers.get("Host") match {
Use gerOrElse(null) to avoid allocation

2024-10-01 18:18 UTC, 987Nabil commented on zio-http/shared/src/main/scala/zio/http/Routes.scala
> +        val allowedMethods = tree.getAllMethods(req.path)
Should be a def, since it is used only once and only if chunk is empty

2024-10-08 00:56 UTC, Saturn225 commented
The failing test is that cors header is adding OPTIONS method automatically in that spec. I will need to take care of this case in toHandler. I'll fix it

2024-10-11 17:01 UTC, Saturn225 commented
The validation added in ServerInboundHandler.scala gone too aggressive for the zioHttpTestKit. Tackling it

2024-10-31 08:36 UTC, Saturn225 commented
@987Nabil Any suggestions on failing tests on ServerSpec?

2024-11-06 20:06 UTC, Saturn225 commented
@987Nabil Any Any guidance here?

2024-11-08 19:34 UTC, 987Nabil commented
Sorry, I am busy these days. I come back to you when I have time.

2024-11-08 19:35 UTC, Saturn225 commented
Thanks @987Nabil

2024-12-11 14:27 UTC, Saturn225 commented
@987Nabil Seems tricky why the entire workflows failing in the repo

2024-12-26 11:21 UTC, Saturn225 commented
@jdegoes @987Nabil Can this get reviewed? It's been open from a long time

2025-01-06 14:09 UTC, Saturn225 commented
@jdegoes @987Nabil Please have a eye on this at your free time?

2025-01-22 17:05 UTC, Saturn225 commented
@jdegoes I wanted to follow up on this PR which has been open for 4 months and is currently blocked by your approval. Could you please take a moment to review it? Your approval would help it move forward 🙏

2025-01-22 21:10 UTC, jdegoes commented
@987Nabil Can you review this, please? 🙏

2025-01-23 07:56 UTC, 987Nabil commented on zio-http/jvm/src/main/scala/zio/http/netty/server/ServerInboundHandler.scala
> +    val host = req.headers.get("Host").getOrElse(null)
```suggestion
    val host = req.headers.getUnsafe("Host")
```

2025-01-23 08:00 UTC, 987Nabil commented on zio-http/jvm/src/main/scala/zio/http/netty/server/ServerInboundHandler.scala
> +      ZIO.logWarning(s"Missing Host header for request ${req.method} ${req.url}")
This is dead code

2025-01-23 08:00 UTC, 987Nabil commented on zio-http/jvm/src/main/scala/zio/http/netty/server/ServerInboundHandler.scala
> +        ZIO
Dead code. Please remove

2025-01-23 08:06 UTC, 987Nabil commented on zio-http/shared/src/main/scala/zio/http/RoutePattern.scala
> +    def getAllMethods(path: Path): Set[Method] = {
```suggestion
    private[http] def getAllMethods(path: Path): Set[Method] = {
```

2025-01-23 08:11 UTC, 987Nabil commented on zio-http/shared/src/main/scala/zio/http/codec/internal/EncoderDecoder.scala
> +              if (codec.name.equalsIgnoreCase("Authorization")) {
why is this needed? That does not seem to change a thing

2025-01-23 08:12 UTC, 987Nabil commented on zio-http/shared/src/main/scala/zio/http/endpoint/Endpoint.scala
> +                  Response.unauthorized.addHeaders(Headers(Header.WWWAuthenticate.Bearer(realm = "Restricted Area"))),
While this needs spezial handling, it is not always the right header to add

2025-01-23 08:14 UTC, 987Nabil commented on zio-http/shared/src/main/scala/zio/http/internal/HeaderModifier.scala
> +    if (header.headerName == Header.XFrameOptions.name) {
special case handling for a deprecated header. Please revert and remove related tests if there are any

2025-01-23 08:27 UTC, 987Nabil commented on zio-http/shared/src/main/scala/zio/http/Routes.scala
> +        def allowedMethods = tree.getAllMethods(req.path)
This can be done more efficient. I think I might open a separate PR for that.

2025-01-23 08:47 UTC, 987Nabil commented on zio-http/shared/src/main/scala/zio/http/Routes.scala
> +        def allowedMethods = tree.getAllMethods(req.path)
@jdegoes @kyri-petrou after giving that a thought, I think we should keep 404 as a default.
It makes it more performant and a default 405 (MethodNotAllowed) could make it easier to find out what routes exist on a server.
If someone needs 405, it can be implemented in user land

2025-01-23 08:51 UTC, 987Nabil commented on zio-http/shared/src/main/scala/zio/http/Routes.scala
> +        def allowedMethods = tree.getAllMethods(req.path)
@Saturn225 please revert this. We decided to keep 404

2025-01-23 09:10 UTC, Saturn225 commented on zio-http/shared/src/main/scala/zio/http/codec/internal/EncoderDecoder.scala
> +              if (codec.name.equalsIgnoreCase("Authorization")) {
@987Nabil It's returning a default 400 Bad Request instead 401 Unauthorized error when header is missing. So we need this to conform RFC to return Unauthorized error with header

2025-01-23 09:11 UTC, Saturn225 commented on zio-http/shared/src/main/scala/zio/http/endpoint/Endpoint.scala
> +                  Response.unauthorized.addHeaders(Headers(Header.WWWAuthenticate.Bearer(realm = "Restricted Area"))),
But to conform this https://datatracker.ietf.org/doc/html/rfc7235#section-3.1 we need to add header along 401. If we need flexibility i remove adding header and instead return only 401

2025-01-23 09:13 UTC, Saturn225 commented on zio-http/shared/src/main/scala/zio/http/internal/HeaderModifier.scala
> +    if (header.headerName == Header.XFrameOptions.name) {
Okay

2025-01-23 09:31 UTC, Saturn225 commented on zio-http/shared/src/main/scala/zio/http/Routes.scala
> +        def allowedMethods = tree.getAllMethods(req.path)
Done!

2025-01-23 10:21 UTC, Saturn225 commented
Done @987Nabil

2025-01-23 13:43 UTC, 987Nabil commented on zio-http/shared/src/main/scala/zio/http/codec/internal/EncoderDecoder.scala
> +              if (codec.name.equalsIgnoreCase("Authorization")) {
But `codec.name` is `authorization` you call the same missing header constructor with the same arguments

2025-01-23 13:44 UTC, 987Nabil commented on zio-http/shared/src/main/scala/zio/http/codec/HttpCodecError.scala
> +    def message = if (headerName.equalsIgnoreCase("Authorization")) "Missing Authorization header"
Please revert. It only changes the order of `header` and `Authorization` for no reason

2025-01-23 13:46 UTC, 987Nabil commented on zio-http/shared/src/main/scala/zio/http/endpoint/Endpoint.scala
> +                  Response.unauthorized.addHeaders(Headers(Header.WWWAuthenticate.Bearer(realm = "Restricted Area"))),
Just keep it unchanged for now and set the test to ignore. This needs a smarter solution

2025-01-23 14:24 UTC, Saturn225 commented on zio-http/shared/src/main/scala/zio/http/endpoint/Endpoint.scala
> +                  Response.unauthorized.addHeaders(Headers(Header.WWWAuthenticate.Bearer(realm = "Restricted Area"))),
Okay! Done

2025-01-23 14:25 UTC, Saturn225 commented on zio-http/shared/src/main/scala/zio/http/codec/HttpCodecError.scala
> +    def message = if (headerName.equalsIgnoreCase("Authorization")) "Missing Authorization header"
Done!

2025-01-23 14:32 UTC, Saturn225 commented
@987Nabil I have cleaned up the PR and marked the test as ignore for now

2025-02-05 15:37 UTC, 987Nabil commented
@kyri-petrou wants to take a look too

2025-03-30 19:06 UTC, Saturn225 commented
@jdegoes @987Nabil @kyri-petrou Can you review this, please? 🙏

2025-05-08 04:49 UTC, 987Nabil commented on zio-http/jvm/src/main/scala/zio/http/netty/server/ServerInboundHandler.scala
> +        ZIO
This is still dead code

2025-05-08 04:50 UTC, 987Nabil commented on zio-http/jvm/src/main/scala/zio/http/netty/server/ServerInboundHandler.scala
> +            if (!validateHostHeader(req)) {
@kyri-petrou I am not sure we should check this here. I think it is overhead and only if we parse it to the typed version we should check it, I think.

2025-05-08 04:56 UTC, Saturn225 commented on zio-http/jvm/src/main/scala/zio/http/netty/server/ServerInboundHandler.scala
> +        ZIO
We are using it at validation

2025-05-08 05:05 UTC, Saturn225 commented
@kyri-petrou Can you review this, please? 🙏

2025-05-09 08:13 UTC, kyri-petrou commented on zio-http/jvm/src/main/scala/zio/http/netty/server/ServerInboundHandler.scala
> +        ZIO
How are you using it in validation? This makes no sense to me

2025-05-09 08:13 UTC, kyri-petrou commented on zio-http/jvm/src/main/scala/zio/http/netty/server/ServerInboundHandler.scala
> +      val isValidHost = parts(0).forall(c => c.isLetterOrDigit || c == '.' || c == '-')
This can be rewritten so that you iterate the string until the first `:` instead of splitting it and then calling `forall`. Also, _do not_ call `forall` on Strings as that will cause each individual char to be boxed

2025-05-09 08:13 UTC, kyri-petrou commented on zio-http/shared/src/main/scala/zio/http/Handler.scala
> +  def notImplemented: Handler[Any, Nothing, Any, Response] =
```suggestion
  val notImplemented: Handler[Any, Nothing, Any, Response] =
```

2025-05-09 08:13 UTC, kyri-petrou commented on zio-http/jvm/src/main/scala/zio/http/netty/server/ServerInboundHandler.scala
> +            if (!validateHostHeader(req)) {
I think the overhead should be relatively very small, although according to [this](https://developer.mozilla.org/en-US/docs/Web/HTTP/Reference/Headers/Host#:~:text=A%20400%20Bad%20Request%20status%20code%20may%20be%20sent%20to%20any%20HTTP/1.1%20request%20message%20that%20lacks%20or%20contains%20more%20than%20one%20Host%20header%20field.) the server _MAY_ respond with 400 if the host header is missing or is invalid.

To be honest I think a better approach would be to add a flag to the config `validateHeaders` (with a default to `false`) which will:
1. set [this](https://github.com/zio/zio-http/blob/22caa5a7920603955a500848edb4fc0ce892c575/zio-http/jvm/src/main/scala/zio/http/netty/server/ServerChannelInitializer.scala#L68) to true
2. enable any custom header validations

2025-05-09 08:13 UTC, kyri-petrou commented on zio-http/jvm/src/main/scala/zio/http/netty/server/ServerInboundHandler.scala
> +            if (!validateHostHeader(req)) {
Also, ideally we want to keep all header validation happening in one place. I think the only way we can do this is by extending the default encoder and adding any additional validation within it.

https://github.com/zio/zio-http/blob/22caa5a7920603955a500848edb4fc0ce892c575/zio-http/jvm/src/main/scala/zio/http/netty/server/ServerChannelInitializer.scala#L63

2025-05-09 08:13 UTC, kyri-petrou commented on zio-http/jvm/src/main/scala/zio/http/netty/server/ServerInboundHandler.scala
> +            if (!validateHostHeader(req)) {
Also, ideally we want to keep all header validation happening in one place. I think the only way we can do this is by extending the default encoder and adding any additional validation within it.

https://github.com/zio/zio-http/blob/22caa5a7920603955a500848edb4fc0ce892c575/zio-http/jvm/src/main/scala/zio/http/netty/server/ServerChannelInitializer.scala#L63

2025-05-25 10:34 UTC, Saturn225 commented
@kyri-petrou @987Nabil Can you review this? Made mima safe approach to introduce validateHeaders flag and all checks are passed now except netifly deployments checks

2025-05-26 12:03 UTC, Saturn225 commented
@kyri-petrou  @987Nabil could you please review/merge PR?

2025-06-18 13:25 UTC, 987Nabil requested changes

2025-06-18 13:25 UTC, 987Nabil commented on zio-http/shared/src/main/scala/zio/http/Server.scala
> +final case class ServerRuntimeConfig(
We can't have a new class ever time we add a config. And while this is bin compatible, it is not source compatible.
It might be more work, but please make the other config a class instead of a case class and write all necessary methods by hand

2025-07-29 09:53 UTC, Excellencedev commented
This is clearly AI slop. TRASH!!!!!!!. Please don't waste your time and close this rubbish

2025-11-30 15:53 UTC, closed without merging