Optimize some `zio.http.endpoint.Endpoint` code
zio/zio-http pull request #3213
Opened 2024-11-19 01:37 UTC by guizmaii

Replace the `NonEmptyChunk.formChunk(...).getOrElse(...)` with `chunk.nonEmptyOrElse(...)(...)`

2024-11-25 11:36 UTC, 987Nabil commented
Please reopen when it builds

2024-11-26 07:32 UTC, guizmaii commented
@987Nabil Should be good now :)

2024-12-02 12:10 UTC, 987Nabil requested changes

2024-12-02 12:10 UTC, 987Nabil commented on zio-http/shared/src/main/scala/zio/http/endpoint/Endpoint.scala
> +) {
Unrelated and unnecessary format change

2024-12-02 12:10 UTC, 987Nabil commented on zio-http/shared/src/main/scala/zio/http/endpoint/Endpoint.scala
> +      authType match {
Unrelated and unnecessary format change

2024-12-05 17:01 UTC, guizmaii commented on zio-http/shared/src/main/scala/zio/http/endpoint/Endpoint.scala
> +) {
Fixed

2024-12-05 17:02 UTC, guizmaii commented on zio-http/shared/src/main/scala/zio/http/endpoint/Endpoint.scala
> +      authType match {
Fixed

2024-12-16 05:33 UTC, 987Nabil requested changes

2024-12-16 05:33 UTC, 987Nabil commented on zio-http/shared/src/main/scala/zio/http/endpoint/Endpoint.scala
> +        NonEmptyChunk(
Can't we make this a constant?

2024-12-24 14:50 UTC, 987Nabil approved these changes

2024-12-24 15:24 UTC, merged