feat: Encode Auth requirements in Endpoint API
zio/zio-http pull request #3266
Opened 2024-12-31 10:16 UTC by mobley-trent

Closes #2592 
/claim #2592

2025-03-10 20:12 UTC, mobley-trent commented
Working on integrating Auth scopes into OpenAPI

2025-03-12 16:50 UTC, 987Nabil requested changes
Might add more later on

2025-03-12 16:50 UTC, 987Nabil commented on zio-http/shared/src/main/scala/zio/http/endpoint/AuthType.scala
> +  private var authScopes: Option[List[String]]  = scala.None
There is no need to have a var here. Please create a new subtype of AuthType that can hold a list of scopes and a auth type.

2025-03-12 16:50 UTC, 987Nabil commented on zio-http/shared/src/main/scala/zio/http/endpoint/AuthType.scala
> +  def getScopes: Option[List[String]]           = authScopes
Please remove the Option. There is no difference between empty List and None.

2025-03-12 16:50 UTC, 987Nabil commented on zio-http/shared/src/main/scala/zio/http/Header.scala
> +      override def name: String = "basicAuth"
This is just wrong. There is no header named "basicAuth" this is "authorization".
Below as well

2025-03-13 13:51 UTC, 987Nabil commented on zio-http/jvm/src/test/scala/zio/http/endpoint/openapi/OpenAPIGenSpec.scala
>    private val endpointWithAuthScopes =
The public API before was okay. Just the internal impl. I wanted you to change. Sorry, I was maybe not clear enough

2025-03-13 13:52 UTC, 987Nabil commented on zio-http/shared/src/main/scala/zio/http/endpoint/Endpoint.scala
> +    case AuthType.ScopedAuth(_, scopes) => scopes
This could be recursive.

2025-03-15 16:30 UTC, 987Nabil commented on zio-http/shared/src/main/scala/zio/http/endpoint/Endpoint.scala
> +  def scopes(scopes: String*): Endpoint[PathInput, Input, Err, Output, AuthType] =
This method should be called with at least one scope and only if the authType is not `AuthType.None`

2025-03-15 16:31 UTC, 987Nabil commented on zio-http/shared/src/main/scala/zio/http/endpoint/Endpoint.scala
> +  def authScopes(authType: AuthType): List[String] = authType match {
The recursive call should only be happening in a private method. The public one should have no params. Also to keep the duality to similar methods, it should be named `scopes`

2025-03-15 16:33 UTC, 987Nabil commented on zio-http/shared/src/main/scala/zio/http/endpoint/AuthType.scala
> +
Please add here methods to add and get scopes. In `Endpoint` there should be just proxies to these.

2025-03-16 13:36 UTC, 987Nabil commented on zio-http/shared/src/main/scala/zio/http/endpoint/AuthType.scala
> +    def getScopes: List[String] = scopes
in the style of zio-http we would call both just `scopes`

2025-03-16 13:37 UTC, 987Nabil commented
Please fix the bin compat. issue reported by mima

2025-03-24 07:55 UTC, 987Nabil approved these changes

2025-03-24 07:56 UTC, merged

2025-03-28 18:34 UTC, mobley-trent commented
@987Nabil does this also close #3183 ?