Feat: decodeContent in Request.apply
zio/zio-http pull request #373
Opened 2021-09-30 05:15 UTC by dinojohn

2021-09-30 11:20 UTC, amitksingh1490 requested changes

2021-09-30 11:20 UTC, amitksingh1490 commented on zio-http/src/main/scala/zhttp/experiment/ContentDecoder.scala
> +sealed trait ContentDecoder[-R, +E, +B] { self =>
`ContentDecoder[R, E, A, B]` A specify type of input

2021-09-30 11:20 UTC, amitksingh1490 commented on zio-http/src/main/scala/zhttp/experiment/ContentDecoder.scala
> +  def getContent(content: ByteBuf): ZIO[R, E, Option[B]]
remove `getContent` in companion object of ContentDecoder use pattern matching

2021-09-30 11:20 UTC, amitksingh1490 commented on zio-http/src/main/scala/zhttp/http/HttpApp.scala
> +                a <- run(Chunk.fromArray(content.array()), nState, isLast)
revert this

2021-09-30 11:20 UTC, amitksingh1490 commented on zio-http/src/main/scala/zhttp/http/Request.scala
> +    content: ByteBuf = Unpooled.EMPTY_BUFFER,
content: A,
use TypeClass and define implicits for Byte, Chunk[Byte], Zstream[R, E, Byte]

2021-10-05 11:38 UTC, dinojohn commented
closing in favour of #381

2021-10-05 11:38 UTC, closed without merging