[WIP] Add IOUring support
zio/zio-http pull request #382
Opened 2021-10-06 03:41 UTC by madper

Howdy Gurus,

I'd using IOUring when possible as it provides better latency. The pr is still WIP. 
However I have a few questions before moving on:

1. Netty-IOUring is still in incubator. It seems we shouldn't use it as default event loop?
2. Should we provide a interface to allow enduser choosing the IOUring manually?

BR

2021-10-06 04:29 UTC, tusharmath commented on zio-http/src/main/scala/zhttp/service/EventLoopGroup.scala
> +      else if (Epoll.isAvailable)
I would not keep `IOUring` as default until it becomes stable.

2021-10-06 04:30 UTC, tusharmath commented
thanks @madper! Looking forward to merging this PR once completed :)

2021-10-08 04:19 UTC, madper commented
Removed iouring from `auto`. Now people who want to use IOUring has to manually use     `.provideCustomLayer(ServerChannelFactory.uring ++ EventLoopGroup.uring(nThreads))` which looks good to me.

2021-10-09 09:04 UTC, madper commented
@tusharmath  As you suggested, now people who want to use iouring needs to appoint it manually.

2021-10-10 17:30 UTC, girdharshubham requested changes

2021-10-10 17:30 UTC, girdharshubham commented on zio-http/src/main/scala/zhttp/service/EventLoopGroup.scala
> +    def uring(nThread: Int): ZManaged[Any, Nothing, channel.EventLoopGroup] =
@madper The EventLoopGroup singleton object is missing the layer for `uring`

2021-10-11 09:36 UTC, madper commented on zio-http/src/main/scala/zhttp/service/EventLoopGroup.scala
> +    def uring(nThread: Int): ZManaged[Any, Nothing, channel.EventLoopGroup] =
Sorry @girdharshubham . Just fixed.

2021-10-11 09:53 UTC, girdharshubham approved these changes
These changes look good to me.
Tested this PR out on a linux machine with kernel version `5.9.0-050900-generic`

2021-10-14 07:20 UTC, girdharshubham requested changes
@madper I think we should keep it as Task[_] instead of UIO[_] because there could be a throwable in the case of Unix-based platforms and kernel version requirement.

2021-10-28 10:46 UTC, tusharmath approved these changes

2021-10-28 10:47 UTC, merged