SocketServerChannel and EventLoopGroup passed via config instead of Layer Dependency
zio/zio-http pull request #461
Opened 2021-11-01 12:28 UTC by sumawa

…ngs) instead of dependency layer

2021-11-01 12:57 UTC, kaushik143 requested changes

2021-11-01 12:57 UTC, kaushik143 commented on zio-http/src/main/scala/zhttp/service/server/TransportFactory.scala
> +    def nio: UIO[JChannelFactory[ServerChannel]]    = ChannelFactory.make(() => new NioServerSocketChannel())
Can this be Task instead of UIO?

2021-11-10 05:35 UTC, tusharmath commented on example/src/main/scala/HelloWorldAdvanced.scala
> +      Server.serverChannel(Transport.Auto)
```suggestion
      Server.nio ++ // (Server.epoll, Server.kqueue, Server.uring, Server.auto)
      Server.threads(nThreads) 
```

2021-11-10 12:43 UTC, tusharmath commented on example/src/main/scala/HelloWorldAdvanced.scala
> +      Server.nThreads(1)              // number of threads for event loop
```suggestion
      Server.threads(1)              // number of threads for event loop
```

2021-11-10 12:48 UTC, tusharmath requested changes

2021-11-10 12:48 UTC, tusharmath commented on zio-http/src/main/scala/zhttp/service/server/TransportFactory.scala
> +sealed trait TransportType
```suggestion
sealed trait Transport
```

2021-11-10 12:48 UTC, tusharmath commented on zio-http/src/main/scala/zhttp/service/server/TransportFactory.scala
> +sealed trait TransportType
```suggestion
sealed trait TransportType {
  def eventLoopGroup: ZManaged[Any, Throwable, EventLoopGroup] = ???  
  def channelInitializer: Task[Any, Throwable, JChannelFactory[ServerChannel]] = ???
}
```

2021-11-11 14:59 UTC, tusharmath commented on zio-http/src/main/scala/zhttp/service/Server.scala
> +      channel        <- ZManaged.fromEffect(Transport.channelInitializer(settings.transport))
```suggestion
      channelFactory        <- ZManaged.fromEffect(settings.transport.channelFactory)
```

2021-11-11 16:07 UTC, tusharmath commented on example/src/main/scala/example/HelloWorldAdvanced.scala
> +      Server.transport(Auto)          // (Server.epoll, Server.kqueue, Server.uring, Server.auto)
```suggestion
      Server.transport(Transport.Auto)          // (Server.epoll, Server.kqueue, Server.uring, Server.auto)
```

Alternative API to do something like 

```scala
Server.nio
```

2021-12-16 07:57 UTC, tusharmath commented
Closing this because the approach might not work when we want to share the event loop between the client and the server.

2021-12-16 07:57 UTC, closed without merging