For main | request changes from release/next
zio/zio-http pull request #557
Opened 2021-11-23 14:25 UTC by ShrutiVerma97

2021-11-23 18:40 UTC, smehta91 requested changes

2021-11-23 18:40 UTC, smehta91 commented on example/src/main/scala/HttpsClient.scala
> +      res.content.map(_.toChar).mkString
Why is this required ?

2021-11-23 18:40 UTC, smehta91 commented on zio-http/src/main/scala/zhttp/http/HttpError.scala
> +  abstract class HTTPErrorWithCause(status: Status, msg: String) extends HttpError(status, msg) {
Unecessary changes

2021-11-23 18:40 UTC, smehta91 commented on zio-http/src/main/scala/zhttp/http/Request.scala
> -  def remoteAddress: Option[InetAddress] = {
We will be removing this functionality. This could be a breaking change.

2021-11-23 18:40 UTC, smehta91 commented on zio-http/src/main/scala/zhttp/service/server/ServerRequestHandler.scala
> +            ctx.write(Unpooled.copiedBuffer(text.getBytes(charset)), ctx.channel().voidPromise())
Why are we using `copiedBuffer` instead of `wrappedBuffer`

2021-11-23 18:42 UTC, smehta91 commented on example/src/main/scala/HttpsClient.scala
> +      res.content.map(_.toChar).mkString
Why are changing the behaviour here ?

2021-11-24 04:23 UTC, amitksingh1490 commented on zio-http/src/main/scala/zhttp/http/HeaderExtension.scala
> +package zhttp.http
this needs to be a seperate PR

2021-11-24 04:25 UTC, amitksingh1490 commented on zio-http/src/main/scala/zhttp/http/HttpData.scala
> +import io.netty.buffer.{ByteBuf, Unpooled}
seperate PR for this file

2021-11-24 04:27 UTC, amitksingh1490 commented on zio-http/src/main/scala/zhttp/http/ResponseHelpers.scala
> +          HttpData.BinaryChunk(cause.cause match {
we can optimise it using HttpData.fromtext

2021-11-24 04:27 UTC, amitksingh1490 commented on zio-http/src/main/scala/zhttp/http/ResponseHelpers.scala
> +      case _ => http(error.status, Nil, HttpData.BinaryChunk(Chunk.fromArray(error.message.getBytes(HTTP_CHARSET))))
we can simpify it using HttpData.fromtext

2021-11-24 04:28 UTC, amitksingh1490 commented on zio-http/src/main/scala/zhttp/http/ResponseHelpers.scala
> +      content = HttpData.BinaryChunk(Chunk.fromArray(text.getBytes(HTTP_CHARSET))),
HttpData.Text should be used

2021-11-24 04:28 UTC, amitksingh1490 commented on zio-http/src/main/scala/zhttp/http/ResponseHelpers.scala
> +      content = HttpData.BinaryChunk(Chunk.fromArray(data.getBytes(HTTP_CHARSET))),
HttpData.text should be used

2021-11-24 11:37 UTC, smehta91 approved these changes, later dismissed

2021-11-24 11:38 UTC, smehta91 approved these changes

2021-11-24 11:38 UTC, merged