Refactor: Server Response Handler
zio/zio-http pull request #666
Opened 2021-12-20 12:58 UTC by gciuloaica

- [x]  Need to resolve one memory leak in the server side content handler.

Closes #648

2021-12-20 13:03 UTC, amitksingh1490 commented
## 🚀🚀🚀 Benchmark Results 
 **Concurrency: 256** 
 **Requests/sec: 474029.17**

2021-12-20 13:07 UTC, amitksingh1490 commented
## 🚀🚀🚀 Benchmark Results 
 **Concurrency: 256** 
 **Requests/sec: 461922.94**

2021-12-21 11:27 UTC, amitksingh1490 commented
## 🚀🚀🚀 Benchmark Results 
 **Concurrency: 256** 
 **Requests/sec: 481289.95**

2021-12-21 11:40 UTC, amitksingh1490 commented
## 🚀🚀🚀 Benchmark Results 
 **Concurrency: 256** 
 **Requests/sec: 474189.59**

2021-12-21 12:34 UTC, amitksingh1490 commented
## 🚀🚀🚀 Benchmark Results 
 **Concurrency: 256** 
 **Requests/sec: 487956.38**

2021-12-22 09:42 UTC, amitksingh1490 commented
## 🚀🚀🚀 Benchmark Results 
 **Concurrency: 256** 
 **Requests/sec: 444277.21**

2021-12-24 10:05 UTC, tusharmath commented on zio-http/src/main/scala/zhttp/http/HttpData.scala
> +  def fromByteBufStream[R, E](stream: ZStream[R, E, ByteBuf]): HttpData[R, E] =
```suggestion
  private [zhttp] def fromByteBufStream[R, E](stream: ZStream[R, E, ByteBuf]): HttpData[R, E] =
```

2021-12-24 10:06 UTC, tusharmath commented on zio-http/src/main/scala/zhttp/service/Handler.scala
> +    val content                              = Unpooled.copiedBuffer(jReq.content())
Why is this required? It's going to affect performance.

ALSO — If heap is the way to go for us, then we can set that configuration one time when the server starts I think.

2021-12-24 10:08 UTC, tusharmath commented on zio-http/src/main/scala/zhttp/service/Server.scala
> +    leakDetectionLevel: LeakDetectionLevel = LeakDetectionLevel.PARANOID,
We shouldn't keep `PARANOID` as default. It affects performance quite badly and most people will deploy this on production without changing the configuration.

2021-12-24 10:11 UTC, tusharmath commented on zio-http/src/main/scala/zhttp/service/server/content/handler/ServerResponseHandler.scala
> +  override def channelRead0(ctx: ChannelHandlerContext, response: Either[Throwable, Response[R, Throwable]]): Unit = {
```suggestion
  override def channelRead0(ctx: ChannelHandlerContext, response: Response[R, Throwable]): Unit = {
```

Let's handle any kind of Response over here.

2021-12-24 10:12 UTC, tusharmath commented on zio-http/src/main/scala/zhttp/service/Handler.scala
> +              unsafeWriteStreamContent(res)
We should move the code to handle `HttpData` also to the ResponseHandler

2021-12-24 10:21 UTC, tusharmath requested changes

2021-12-24 10:21 UTC, tusharmath commented on zio-http/src/main/scala/zhttp/service/server/content/handler/ServerResponseHandler.scala
> +    ctx.writeAndFlush(serverErrorResponse(cause)): Unit
needs unit tests. Also this won't really fix #686. Reason being — Once the connection is closed, you can't write anything more on the channel. That's the reason you got this error in the first place.

2021-12-27 13:03 UTC, gciuloaica commented
@tusharmath I will close this PR as a did another implementation from scratch today.

2021-12-27 13:03 UTC, closed without merging