Documentation: Http
zio/zio-http pull request #888
Opened 2022-01-24 05:03 UTC by dinojohn

2022-01-26 14:50 UTC, amitksingh1490 commented on docs/website/docs/v1.x/dsl/http/index.md
> +#HTTP
```suggestion
# Http Domain
```

2022-01-26 14:50 UTC, amitksingh1490 commented on docs/website/docs/v1.x/dsl/http/index.md
> +HTTP is a functional domain to model Http apps using ZIO. It can work over any kind of request and response type.
```suggestion
`Http` is a functional domain that models Http apps using ZIO. It can work over any kind of request and response type.
```

2022-01-26 14:53 UTC, amitksingh1490 commented on docs/website/docs/v1.x/dsl/http/index.md
> +A `Http[-R, +E, -A, +B]` is essentially a function form `A` to `ZIO[R, Option[E], B]`. Whereas `HttpApp[-R, +E]` is a function from `Request` to `ZIO[R, E, Response]`. To start a zio-http server we n
```suggestion
A `Http[-R, +E, -A, +B]` models a function from `A` to `ZIO[R, Option[E], B]`. Whereas `HttpApp[-R, +E]` is a function from `Request` to `ZIO[R, Option[E], Response]`. ZIO HTTP server works on `HttpApp[R, E]`.
```

2022-01-26 14:54 UTC, amitksingh1490 commented on docs/website/docs/v1.x/dsl/http/index.md
> +There are several operators and constructors to model the application as required.
```suggestion
`Http` domain provides several operators and constructors to model the application as per your use case.
```

2022-01-26 14:55 UTC, amitksingh1490 commented on docs/website/docs/v1.x/dsl/http/index.md
> +Here are some of the simple constructors to make useful Http applications.
```suggestion
These are some of the constructors to make `HTTP` applications.
```

2022-01-26 14:55 UTC, amitksingh1490 commented on docs/website/docs/v1.x/dsl/http/index.md
> +Creates an Http app that always fails with the given value.
```suggestion
Creates an Http app that always fails with the given error.
```

2022-01-26 14:56 UTC, amitksingh1490 commented on docs/website/docs/v1.x/dsl/http/index.md
> +Creates an Http that always returns the same response and never fails.
```suggestion
Creates an Http that never fails and always returns the same output.
```

2022-01-26 14:58 UTC, amitksingh1490 commented on docs/website/docs/v1.x/dsl/http/index.md
> +##HTTP Constructors
```suggestion
## HTTP Constructors
```

2022-01-27 03:39 UTC, amitksingh1490 commented on docs/website/docs/v1.x/dsl/http/index.md
> +These are some constructors to make `HTTP` applications.
```suggestion
These are some constructors to make HTTP applications.
```

2022-01-27 03:39 UTC, amitksingh1490 commented on docs/website/docs/v1.x/dsl/http/index.md
> +Creates an `HTTP` app that always fails with the given error.
```suggestion
Creates an HTTP app that always fails with the given error.
```

2022-01-27 03:40 UTC, amitksingh1490 commented on docs/website/docs/v1.x/dsl/http/index.md
> +Creates an `HTTP` that always returns the same response and never fails.
```suggestion
Creates an HTTP that always returns the same response and never fails.
```

2022-01-27 04:16 UTC, amitksingh1490 requested changes

2022-01-27 04:16 UTC, amitksingh1490 commented on docs/website/docs/v1.x/dsl/http/index.md
> +Creates an `HTTP` app that always responds with the same plain text.
```suggestion
Creates an HTTP app that always responds with the same plain text.
```

2022-01-27 04:16 UTC, amitksingh1490 commented on docs/website/docs/v1.x/dsl/http/index.md
> +### Http.fail()
```suggestion
### Http.fail
```

2022-01-27 04:16 UTC, amitksingh1490 commented on docs/website/docs/v1.x/dsl/http/index.md
> +### Http.succeed ()
```suggestion
### Http.succeed
```

2022-01-27 04:16 UTC, amitksingh1490 commented on docs/website/docs/v1.x/dsl/http/index.md
> +### Http.text ()
```suggestion
### Http.text
```

2022-01-27 04:16 UTC, amitksingh1490 commented on docs/website/docs/v1.x/dsl/http/index.md
> +constructors to create `HTTP` applications from total as well as partial functions.
```suggestion
You can also create an HTTP application from total and partial functions. These are some constructors to create HTTP applications from the total as well as partial functions.
```

2022-01-27 04:16 UTC, amitksingh1490 commented on docs/website/docs/v1.x/dsl/http/index.md
> +### Http.collect ()
```suggestion
### Http.collect
```

2022-01-27 04:16 UTC, amitksingh1490 commented on docs/website/docs/v1.x/dsl/http/index.md
> +Http.Collect() can create an `Http[Any, Nothing, A, B]` from a `PartialFunction[A, B]`. In case an input is not defined
```suggestion
`Http.Collect` can create an `Http[Any, Nothing, A, B]` from a `PartialFunction[A, B]`. In case an input is not defined
```

2022-01-27 04:16 UTC, amitksingh1490 commented on docs/website/docs/v1.x/dsl/http/index.md
> +for the partial function, the application will return a 404 error.
```suggestion
for the partial function, the application will return a None type error.
```

2022-01-27 04:16 UTC, amitksingh1490 commented on docs/website/docs/v1.x/dsl/http/index.md
> +### Http.collectZIO ()
```suggestion
### Http.collectZIO
```

2022-01-27 04:16 UTC, amitksingh1490 commented on docs/website/docs/v1.x/dsl/http/index.md
> +Http.CollectZIO() can be used to create a `Http[R, E, A, B]` from a partial function that returns a ZIO effect,
```suggestion
`Http.CollectZIO` can be used to create a `Http[R, E, A, B]` from a partial function that returns a ZIO effect, This constructor is used when the output is effectful.
```

2022-01-27 04:16 UTC, amitksingh1490 commented on docs/website/docs/v1.x/dsl/http/index.md
> +### Http.fromFunction ()
```suggestion
### Http.fromFunction
```

2022-01-27 04:16 UTC, amitksingh1490 commented on docs/website/docs/v1.x/dsl/http/index.md
> +Http.fromFunction() can create an `Http[Any, Nothing, A, B]` from a function `f: A=>B`.
```suggestion
`Http.fromFunction` can create an `Http[Any, Nothing, A, B]` from a function `f: A=>B`.
```

2022-01-27 04:16 UTC, amitksingh1490 commented on docs/website/docs/v1.x/dsl/http/index.md
> +### Http.fromFunctionZIO ()
```suggestion
### Http.fromFunctionZIO
```

2022-01-27 04:16 UTC, amitksingh1490 commented on docs/website/docs/v1.x/dsl/http/index.md
> +Http.fromFunctionZIO() can create a `Http[R, E, A, B]` from a function that returns a ZIO effect,
```suggestion
`Http.fromFunctionZIO` can create a `Http[R, E, A, B]` from a function that returns a ZIO effect,
```

2022-01-27 04:16 UTC, amitksingh1490 commented on docs/website/docs/v1.x/dsl/http/index.md
> +Http applications.
```suggestion
There are many more constructors in the `Http` Domain. 
Some for creating `HttpApp[R,E]` and remaining for creating `Http[R,E,A,B]`. Kindly check out the examples for more HTTP applications.
```
Please add a hyperlink for examples section

2022-01-27 04:16 UTC, amitksingh1490 commented on docs/website/docs/v1.x/dsl/http/index.md
> +### map ()
remove paranthesis from function names and headings everywhere

2022-01-27 04:16 UTC, amitksingh1490 commented on docs/website/docs/v1.x/dsl/http/index.md
> +Combines two `HTTP` applications into one.
explain a bit more and talk about its alias `++` in this section

2022-01-27 04:16 UTC, amitksingh1490 commented on docs/website/docs/v1.x/dsl/http/index.md
> +### andThen ()
explain a bit more and talk about its alias in this section

2022-01-27 04:16 UTC, amitksingh1490 commented on docs/website/docs/v1.x/dsl/http/index.md
> +### execute ()
remove this as its private to method

2022-01-27 04:16 UTC, amitksingh1490 commented on docs/website/docs/v1.x/dsl/http/index.md
> +### execute ()
May be you can use this in the top to explain how Http is executed

2022-01-27 04:16 UTC, amitksingh1490 commented on docs/website/docs/v1.x/dsl/http/index.md
> +Attaches the provided middleware to the `HttpApp`
named alias also it works on Http as well as HttpApp

2022-01-31 09:14 UTC, amitksingh1490 commented on docs/website/docs/v1.x/dsl/http/index.md
> +from `Request` to `ZIO[R, Option[E], Response]`. ZIO HTTP server works on `HttpApp[R, E]`. When a value of type `A` is
```suggestion
A `Http[-R, +E, -A, +B]` models a function from `A` to `ZIO[R, Option[E], B]`. 
`HttpApp[-R, +E]` is a type alias for `Http[R, E, Request, Response]. 
ZIO HTTP server runs only `HttpApp[R, E]`, If you want to run any other `Http[R, E, A,B]` on ZIO HTTP server you need to convert it to `HttpApp[R, E]` using operators like `map`,`contramap`, `middleware`, etc. as explained in upcoming sections.
 When a value of type `A` is
```

2022-01-31 09:15 UTC, amitksingh1490 commented on docs/website/docs/v1.x/dsl/http/index.md
> +```
Add a section to cover Http to HttpApp using map, contramap, mapzio, contramapZIO, middleware etc.

2022-01-31 09:24 UTC, amitksingh1490 commented
The flow of the documentation doesn't feel like I am reading a book It feels like a scaladoc
flow can be something like.
-What is Http?
- Http
    - Creating Http 
    - Handling Errors
    - Providing environments 
    -  Attaching Middleware
    - Unit testing
    - ...
- What is HttpApp?
    - Special Constructors for HttpApp
    - Special Operators on HttpApp
- Converting a Http to HttpApp
    - map contramap
    - middleware  
- Running a HttpApp

2022-02-02 05:53 UTC, amitksingh1490 commented on docs/website/docs/v1.x/dsl/http/index.md
> +```scala
Http examples should not use request response we could use in HttpApp examples

2022-02-02 05:54 UTC, amitksingh1490 commented on docs/website/docs/v1.x/dsl/http/index.md
> +## More Operators
```suggestion
## Transforming Http Applications
```

2022-02-02 05:56 UTC, amitksingh1490 commented on docs/website/docs/v1.x/dsl/http/index.md
> +## Converting an `Http` to `HttpApp`
Add section where you can use codec middleware for conversion

2022-02-02 05:59 UTC, amitksingh1490 requested changes

2022-02-02 05:59 UTC, amitksingh1490 commented on docs/website/docs/v1.x/dsl/http/index.md
> +  val app1 = Http.succeed("text")
add types for app1 and app2
rename app1 to a and app2 to b

2022-02-02 13:20 UTC, ShrutiVerma97 commented on docs/website/docs/v1.x/dsl/http/index.md
> +evaluated against an `Http[R,E,A,B]`, internally a private method `execute` will be called and an `HExit` value is
Don't include internal methods in doc.

2022-02-02 18:59 UTC, ShrutiVerma97 commented
looks good to me

2022-02-02 19:06 UTC, amitksingh1490 approved these changes

2022-02-02 19:06 UTC, merged