WebSocket Client Support
zio/zio-http pull request #933
Opened 2022-02-01 08:02 UTC by tusharmath

2022-02-02 12:01 UTC, tusharmath commented on zio-http/src/main/scala/zhttp/http/Request.scala
> +    val hostHeaders = (url.host, url.port) match {
I don't think this is required.

2022-02-02 12:01 UTC, tusharmath commented on zio-http/src/main/scala/zhttp/http/Request.scala
> +    val hostHeaders = (url.host, url.port) match {
I don't think this is required.

2022-02-02 12:11 UTC, tusharmath commented on zio-http/src/test/scala/zhttp/http/RequestSpec.scala
> +object RequestSpec extends DefaultRunnableSpec {
Delete RequestSpec

2022-02-02 12:13 UTC, tusharmath commented on zio-http/src/test/scala/zhttp/internal/HttpGen.scala
> +  def jWebSocketScheme: Gen[Any, WebSocketScheme] = Gen.fromIterable(List(WebSocketScheme.WS, WebSocketScheme.WSS))
Let's move the netty gens close to the tests and move it out of this file. This file is only for ZIO Http Gens.

2022-02-02 12:14 UTC, tusharmath commented on zio-http/src/test/scala/zhttp/service/WebSocketServerSpec.scala
> +        assertM(allTrue)(equalTo(1024))
Simplify code like it was before.

2022-02-04 08:52 UTC, amitksingh1490 commented on zio-http/src/main/scala/zhttp/http/Scheme.scala
> +  def toWebSocketScheme: Option[WebSocketScheme] = self match {
```suggestion
  def toJWebSocketScheme: Option[WebSocketScheme] = self match {
```
for consistency in nomenclature

2022-02-04 09:04 UTC, amitksingh1490 approved these changes

2022-02-04 09:53 UTC, girdharshubham requested changes

2022-02-04 09:53 UTC, girdharshubham commented on zio-http/src/test/scala/zhttp/service/WebSocketServerSpec.scala
> +          .map(r => r.count(_ == Status.SWITCHING_PROTOCOLS))
```suggestion
          .map(_.count(_ == Status.SWITCHING_PROTOCOLS))
```

2022-02-04 09:58 UTC, girdharshubham commented on zio-http/src/main/scala/zhttp/service/Client.scala
> +          if (isSSL) pipeline.addLast("SSLHandler", ClientSSLHandler.ssl(sslOption).newHandler(ch.alloc))
Pick it from the package object

2022-02-04 10:10 UTC, girdharshubham commented on zio-http/src/main/scala/zhttp/http/Scheme.scala
> +  def toWebSocketScheme: Option[WebSocketScheme] = self match {
This is done. Thanks, Amit.

2022-02-04 10:15 UTC, girdharshubham approved these changes

2022-02-04 11:30 UTC, amitksingh1490 approved these changes

2022-02-04 11:30 UTC, merged