Refactor: ServerSSLHandler
zio/zio-http pull request #972
Opened 2022-02-07 09:44 UTC by dinojohn

This PR enables further customisations for SSlContext. This is also a supporting PR for http2.

2022-03-02 05:20 UTC, smehta91 requested changes

2022-03-02 05:20 UTC, smehta91 commented on zio-http/src/main/scala/zhttp/service/server/ServerSSLBuilder.scala
> +    if (enableHttp2) {
Test is missing for this condition.

2022-03-02 05:20 UTC, smehta91 commented on zio-http/src/main/scala/zhttp/service/server/ServerSSLBuilder.scala
> +        .ciphers(Http2SecurityUtil.CIPHERS, SupportedCipherSuiteFilter.INSTANCE)
I think we should use `builder pattern` to build the arguments (eg. ciphers, ApplicationProtocolConfig) for`SSLContextBuilder` and that should have `build` method which actually calls `sslContextBuilder`

2022-04-14 17:37 UTC, dinojohn commented
on hold for now

2022-04-14 17:37 UTC, closed without merging