Documentation for HttpData
zio/zio-http pull request #987
Opened 2022-02-09 09:53 UTC by dinojohn

Documentation for HttpData

2022-02-09 13:15 UTC, ShrutiVerma97 commented on docs/website/docs/v1.x/dsl/http-data/index.md
> +`HttpData` is a domain to model the content that is to be written in HttpChannel. `HttpRequest` and `HttpResponse` store content as `ByteBuf`. `HttpData` helps you decode and encode this content into
on the Netty's HttpChannel.

2022-02-09 13:22 UTC, ShrutiVerma97 commented on docs/website/docs/v1.x/dsl/http-data/index.md
> +`HttpData` can be created using a lot of constructors.
This line can be removed.

2022-02-09 13:29 UTC, ShrutiVerma97 requested changes

2022-02-09 13:29 UTC, ShrutiVerma97 commented on docs/website/docs/v1.x/dsl/http-data/index.md
> +To attach data to a response you can use the `Response` constructors.
```suggestion
To add data to a response you can use the `Response` constructors that takes `HttpData.Empty` as the default value
```

2022-02-09 13:29 UTC, ShrutiVerma97 commented on docs/website/docs/v1.x/dsl/http-data/index.md
> +To attach data to a request you can use the `Response` constructors.
Same as above.

2022-02-09 13:29 UTC, ShrutiVerma97 commented on docs/website/docs/v1.x/dsl/http-data/index.md
> +### Creating an empty HttpData
We can remove this para

2022-02-09 13:30 UTC, ShrutiVerma97 commented on docs/website/docs/v1.x/dsl/http-data/index.md
> +To convert an `HttpData` to `ButrBuf`  you can call the `toButeBuf` method on it, which returns a `Task[ByteBuf]`.
```suggestion
To convert an `HttpData` to `ByteBuf`  you can call the `toButeBuf` method on it, which returns a `Task[ByteBuf]`.
```

2022-02-09 13:33 UTC, ShrutiVerma97 commented on docs/website/docs/v1.x/dsl/http-data/index.md
> +On the client-side, `ZIO-HTTP` is adding `HttpData.Empty` as the pre-defined data to the `Request`. You may replace it with another `HttpData`.
we can mention, for testing purposes we can use.

2022-02-09 16:38 UTC, amitksingh1490 commented on docs/website/docs/v1.x/dsl/http-data/index.md
> +To attach content while creating a `Response` you can use the `Response` constructor.
```suggestion
To add content while creating a `Response` you can use the `Response` constructor.
```

2022-02-09 16:40 UTC, amitksingh1490 approved these changes

2022-02-10 06:30 UTC, ShrutiVerma97 approved these changes

2022-02-10 06:31 UTC, merged